version: '3'
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
    - ./data/mongo:/data/db

  cache:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/var/lib/redis

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
    - 5775:5775/udp
    - 6831:6831/udp
    - 6832:6832/udp
    - 5778:5778
    - 16686:16686
    - 14268:14268 