// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package oidc

import (
	"encoding/json"
)

// MarshalJSON marshals as JSON.
func (c ClientRegistrationResponse) MarshalJSON() ([]byte, error) {
	type ClientRegistrationResponse struct {
		ClientID                string `json:"client_id,omitempty"`
		ClientIDIssuedAt        int64  `json:"client_id_issued_at,omitempty"`
		ClientSecret            string `json:"client_secret,omitempty"`
		ClientSecretExpiresAt   int64  `json:"client_secret_expires_at,omitempty"`
		RegistrationAccessToken string `json:"registration_access_token,omitempty"`
		RegistrationClientURI   string `json:"registration_client_uri,omitempty"`
	}
	var enc ClientRegistrationResponse
	enc.ClientID = c.ClientID
	enc.ClientIDIssuedAt = c.ClientIDIssuedAt
	enc.ClientSecret = c.ClientSecret
	enc.ClientSecretExpiresAt = c.ClientSecretExpiresAt
	enc.RegistrationAccessToken = c.RegistrationAccessToken
	enc.RegistrationClientURI = c.RegistrationClientURI
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (c *ClientRegistrationResponse) UnmarshalJSON(input []byte) error {
	type ClientRegistrationResponse struct {
		ClientID                *string `json:"client_id,omitempty"`
		ClientIDIssuedAt        *int64  `json:"client_id_issued_at,omitempty"`
		ClientSecret            *string `json:"client_secret,omitempty"`
		ClientSecretExpiresAt   *int64  `json:"client_secret_expires_at,omitempty"`
		RegistrationAccessToken *string `json:"registration_access_token,omitempty"`
		RegistrationClientURI   *string `json:"registration_client_uri,omitempty"`
	}
	var dec ClientRegistrationResponse
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.ClientID != nil {
		c.ClientID = *dec.ClientID
	}
	if dec.ClientIDIssuedAt != nil {
		c.ClientIDIssuedAt = *dec.ClientIDIssuedAt
	}
	if dec.ClientSecret != nil {
		c.ClientSecret = *dec.ClientSecret
	}
	if dec.ClientSecretExpiresAt != nil {
		c.ClientSecretExpiresAt = *dec.ClientSecretExpiresAt
	}
	if dec.RegistrationAccessToken != nil {
		c.RegistrationAccessToken = *dec.RegistrationAccessToken
	}
	if dec.RegistrationClientURI != nil {
		c.RegistrationClientURI = *dec.RegistrationClientURI
	}
	return nil
}
