// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package client

import (
	database "github.com/alextanhongpin/go-openid/internal/database"
	model "github.com/alextanhongpin/go-openid/model"
	repository "github.com/alextanhongpin/go-openid/repository"
	wire "github.com/google/go-cloud/wire"
)

// Injectors from wire.go:

func New() *Service {
	client := provideModel()
	repositoryClient := provideRepository()
	service := NewService(client, repositoryClient)
	return service
}

// wire.go:

var clientServiceSet = wire.NewSet(
	provideRepository,
	provideModel,
	NewService,
)

func provideRepository() repository.Client {
	return database.NewClientKV()
}

func provideModel() model.Client {
	return NewModel()
}
