// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package client

import (
	database "github.com/alextanhongpin/go-openid/internal/database"
	schema "github.com/alextanhongpin/go-openid/pkg/schema"
)

// Injectors from wire.go:

func NewService(arg map[string]schema.Validator) *clientServiceImpl {
	clientKV := database.NewClientKV()
	clientClientModelImpl := NewClientModelImpl(clientKV, arg)
	clientClientServiceImpl := NewClientServiceImpl(clientClientModelImpl)
	return clientClientServiceImpl
}

func NewSimplerService(arg map[string]schema.Validator) *clientServiceImpl {
	clientKV := ProvideRepository()
	clientClientModelImpl := ProvideModel(clientKV, arg)
	clientClientServiceImpl := ProvideService(clientClientModelImpl)
	return clientClientServiceImpl
}
