// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package core

import (
	database "github.com/alextanhongpin/go-openid/internal/database"
	model "github.com/alextanhongpin/go-openid/model"
	repository "github.com/alextanhongpin/go-openid/repository"
	wire "github.com/google/go-cloud/wire"
)

// Injectors from wire.go:

func New() *serviceImpl {
	codeKV := provideCodeRepository()
	clientKV := provideClientRepository()
	userKV := provideUserRepository()
	coreModelImpl := provideModel(codeKV, clientKV, userKV)
	coreServiceImpl := provideService(coreModelImpl)
	return coreServiceImpl
}

// wire.go:

var serviceSet = wire.NewSet(
	provideClientRepository, wire.Bind(new(repository.Client), new(database.ClientKV)), provideCodeRepository, wire.Bind(new(repository.Code), new(database.CodeKV)), provideUserRepository, wire.Bind(new(repository.User), new(database.UserKV)), provideModel, wire.Bind(new(model.Core), new(modelImpl)), provideService,
)

func provideClientRepository() *database.ClientKV {
	return database.NewClientKV()
}

func provideCodeRepository() *database.CodeKV {
	return database.NewCodeKV()
}

func provideUserRepository() *database.UserKV {
	return database.NewUserKV()
}

func provideModel(code repository.Code, client repository.Client, user repository.User) *modelImpl {
	return &modelImpl{code, client, user}
}

func provideService(model2 model.Core) *serviceImpl {
	return &serviceImpl{model2}
}
