// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package user

import (
	database "github.com/alextanhongpin/go-openid/internal/database"
	model "github.com/alextanhongpin/go-openid/pkg/model"
	repository "github.com/alextanhongpin/go-openid/pkg/repository"
	wire "github.com/google/go-cloud/wire"
)

// Injectors from wire.go:

func NewService() *userServiceImpl {
	userKV := provideRepository()
	userUserModelImpl := provideModel(userKV)
	userUserServiceImpl := provideService(userUserModelImpl)
	return userUserServiceImpl
}

// wire.go:

var userServiceSet = wire.NewSet(
	provideRepository, wire.Bind(new(repository.User), new(database.UserKV)), provideModel, wire.Bind(new(model.User), new(userModelImpl)), provideService,
)

func provideRepository() *database.UserKV {
	return database.NewUserKV()
}

func provideModel(repo repository.User) *userModelImpl {
	return &userModelImpl{repository: repo}
}

func provideService(model2 model.User) *userServiceImpl {
	decorateValidator := &userValidatorImpl{model: model2}
	return &userServiceImpl{model: decorateValidator}
}
