// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package user

import (
	database "github.com/alextanhongpin/go-openid/internal/database"
	repository "github.com/alextanhongpin/go-openid/repository"
	wire "github.com/google/go-cloud/wire"
)

// Injectors from user.go:

func New() *Service {
	userKV := provideRepository()
	service := provideService(userKV)
	return service
}

// user.go:

var serviceSet = wire.NewSet(
	provideRepository, wire.Bind(new(repository.User), new(database.UserKV)), provideService,
)

func provideRepository() *database.UserKV {
	return database.NewUserKV()
}

func provideService(repository2 repository.User) *Service {
	return &Service{
		repository: repository2,
	}
}
